### ISSUE TITLE
Step files maybe?

### ISSUE THREAD

**Issue by RicInNewMexico** [philosiraptor/devtermfieldops-#1]
Any chance you'd consider sharing the step files so changes can be made?

I'd **really** like to convert it over to using heat set threaded inserts for a cleaner look. I'd be happy to make the changes and then submit a pull request to have the modified files added to your repo here on github.

**Comment by philosiraptor** [comment]
I WILL GRANT THIS WISH

**Comment by RicInNewMexico** [comment]
Very clean step files! Thanks!

My devterm doesn't even arrive until next week and I'm already working on devterm related projects lol..
